/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author LOZADA
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        Login_Bg_Form = new Vistas.PanelRound(0, 20, 0, 20);
        Login_Title = new javax.swing.JLabel();
        Login_UserLabel = new javax.swing.JLabel();
        Login_UserInput = new javax.swing.JTextField();
        Separador1 = new javax.swing.JSeparator();
        Login_PasswordLabel = new javax.swing.JLabel();
        Separador2 = new javax.swing.JSeparator();
        Login_PasswordInput = new javax.swing.JPasswordField();
        Login_Btn = new Vistas.PanelRound(10, 10, 10, 10);
        Login_BtnText = new javax.swing.JLabel();
        LoginImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Bg_Form.setBackground(new java.awt.Color(78, 69, 189));
        Login_Bg_Form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Title.setBackground(new java.awt.Color(255, 255, 255));
        Login_Title.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        Login_Title.setForeground(new java.awt.Color(255, 255, 255));
        Login_Title.setText("Iniciar Sesión");
        Login_Bg_Form.add(Login_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        Login_UserLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        Login_UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        Login_UserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Imagenes/Iconos/User.png"))); // NOI18N
        Login_UserLabel.setText("Usuario");
        Login_Bg_Form.add(Login_UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        Login_UserInput.setBackground(new java.awt.Color(78, 69, 189));
        Login_UserInput.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Login_UserInput.setForeground(new java.awt.Color(153, 153, 153));
        Login_UserInput.setText("Ingrese su usuario");
        Login_UserInput.setToolTipText("");
        Login_UserInput.setBorder(null);
        Login_Bg_Form.add(Login_UserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 210, -1));

        Separador1.setBackground(new java.awt.Color(78, 69, 189));
        Separador1.setForeground(new java.awt.Color(255, 255, 255));
        Login_Bg_Form.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, -1));

        Login_PasswordLabel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        Login_PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        Login_PasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Imagenes/Iconos/Lock.png"))); // NOI18N
        Login_PasswordLabel.setText("Contraseña");
        Login_Bg_Form.add(Login_PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        Separador2.setBackground(new java.awt.Color(78, 69, 189));
        Separador2.setForeground(new java.awt.Color(255, 255, 255));
        Login_Bg_Form.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 210, -1));

        Login_PasswordInput.setBackground(new java.awt.Color(78, 69, 189));
        Login_PasswordInput.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Login_PasswordInput.setForeground(new java.awt.Color(153, 153, 153));
        Login_PasswordInput.setText("jPasswordField1");
        Login_PasswordInput.setBorder(null);
        Login_Bg_Form.add(Login_PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 210, -1));

        Login_Btn.setBackground(new java.awt.Color(56, 53, 122));

        Login_BtnText.setBackground(new java.awt.Color(56, 53, 122));
        Login_BtnText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Login_BtnText.setForeground(new java.awt.Color(255, 255, 255));
        Login_BtnText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_BtnText.setText("Iniciar");
        Login_BtnText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Login_BtnLayout = new javax.swing.GroupLayout(Login_Btn);
        Login_Btn.setLayout(Login_BtnLayout);
        Login_BtnLayout.setHorizontalGroup(
            Login_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login_BtnText, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        Login_BtnLayout.setVerticalGroup(
            Login_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login_BtnText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        Login_Bg_Form.add(Login_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, 35));

        Bg.add(Login_Bg_Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 500));

        LoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Imagenes/LoginImage.png"))); // NOI18N
        Bg.add(LoginImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel LoginImage;
    private javax.swing.JPanel Login_Bg_Form;
    private javax.swing.JPanel Login_Btn;
    private javax.swing.JLabel Login_BtnText;
    private javax.swing.JPasswordField Login_PasswordInput;
    private javax.swing.JLabel Login_PasswordLabel;
    private javax.swing.JLabel Login_Title;
    private javax.swing.JTextField Login_UserInput;
    private javax.swing.JLabel Login_UserLabel;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    // End of variables declaration//GEN-END:variables
}
