 
package com.myapp.appacademico.Vistas;
 
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JFrame;
import javax.swing.JPanel;  

 
public class VistaRun extends javax.swing.JFrame {
    VistaLogin loginPanel;
    VistaRegister registerPanel;
    VistaHome homePanel;
    
    public VistaRun() {
        initComponents();
        init();
    }
    
    void init() {
        loginPanel = new VistaLogin(this);
        /*registerPanel = new VistaRegister(this);  */
        homePanel = new VistaHome(this);
        changeContent(loginPanel);
    }
    
    public void changeContent(JPanel newPanel) {
        changeContent(newPanel, 810, 500);  
    }
    
    public void changeContent(JPanel newPanel, int width, int height) {
        content.removeAll();
        content.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();

        if (newPanel instanceof VistaHome) {
            newPanel.setPreferredSize(new Dimension(width, height));
            content.setLayout(new BorderLayout());
            content.add(newPanel, BorderLayout.CENTER);
            this.setLocationRelativeTo(null);
        } else {
           
            newPanel.setPreferredSize(new Dimension(width, height));
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            gbc.anchor = GridBagConstraints.CENTER;
            content.add(newPanel, gbc);
        }

        content.revalidate();
        content.repaint();

        if ((this.getExtendedState() & JFrame.MAXIMIZED_BOTH) != JFrame.MAXIMIZED_BOTH) {
            Insets frameInsets = this.getInsets();
            int totalWidth = width + frameInsets.left + frameInsets.right;
            int totalHeight = height + 30 + frameInsets.top + frameInsets.bottom;
            this.setSize(totalWidth, totalHeight);
            this.setLocationRelativeTo(null);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(810, 500));
        content.setPreferredSize(new java.awt.Dimension(810, 500));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    // End of variables declaration//GEN-END:variables
}
